# Generated by Django 4.2.3 on 2023-08-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
    ]
