# Generated by Django 4.2.3 on 2023-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='startPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
