# Generated by Django 4.2.3 on 2023-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_startprice_alter_auction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
