# Generated by Django 4.2.3 on 2023-08-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_currentprice_alter_auction_startprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
