# Generated by Django 4.2.3 on 2023-08-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
