# Generated by Django 4.2.3 on 2023-08-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_currentprice_alter_auction_startprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imageURL',
            field=models.URLField(default=None),
        ),
    ]
